name: Calculate Options Data
on:
  workflow_run:
    workflows: ["Clean Options Data"]
    types:
      - completed
  workflow_dispatch:
jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scipy joblib statsmodels
    - name: Create data directory
      run: mkdir -p data
    - name: Log timestamp and input files
      run: |
        python -c "
        import glob
        import os
        timestamp_dirs = [d for d in glob.glob('data/*') if os.path.isdir(d) and d.split('/')[-1].replace('_', '').isdigit() and len(d.split('/')[-1]) == 13]
        if not timestamp_dirs:
            print('No timestamp folders found')
            sys.exit(1)
        latest_timestamp_dir = max(timestamp_dirs, key=os.path.getctime)
        timestamp = os.path.basename(latest_timestamp_dir)
        print(f'Running calculate_data.py with timestamp: {timestamp}')
        os.system(f'ls -R data/{timestamp}/cleaned_yfinance* || echo \"No cleaned files found\"')
        os.system(f'ls -R data/{timestamp}/raw_yfinance* || echo \"No raw files found\"')
        os.system(f'ls -R data/{timestamp}/historic* || echo \"No historic files found\"')
        "
    - name: Run calculate script
      run: |
        python -c "
        import glob
        import os
        timestamp_dirs = [d for d in glob.glob('data/*') if os.path.isdir(d) and d.split('/')[-1].replace('_', '').isdigit() and len(d.split('/')[-1]) == 13]
        if not timestamp_dirs:
            print('No timestamp folders found')
            sys.exit(1)
        latest_timestamp_dir = max(timestamp_dirs, key=os.path.getctime)
        timestamp = os.path.basename(latest_timestamp_dir)
        os.system(f'python calculate_data.py')
        "
    - name: Log output files
      run: |
        python -c "
        import glob
        import os
        timestamp_dirs = [d for d in glob.glob('data/*') if os.path.isdir(d) and d.split('/')[-1].replace('_', '').isdigit() and len(d.split('/')[-1]) == 13]
        if not timestamp_dirs:
            print('No timestamp folders found')
            sys.exit(1)
        latest_timestamp_dir = max(timestamp_dirs, key=os.path.getctime)
        timestamp = os.path.basename(latest_timestamp_dir)
        print('Processed files:')
        os.system(f'ls -R data/{timestamp}/processed_yfinance* || echo \"No processed files found\"')
        print('Skew metrics files:')
        os.system(f'ls -R data/{timestamp}/skew_metrics_yfinance* || echo \"No skew metrics files found\"')
        print('Slope metrics files:')
        os.system(f'ls -R data/{timestamp}/slope_metrics_yfinance* || echo \"No slope metrics files found\"')
        print('Vol fit file:')
        os.system(f'ls -R data/{timestamp}/vol_fit* || echo \"No vol fit file found\"')
        os.system(f'ls data_error.log || echo \"No error log generated\"')
        "
    - name: Commit and push updated data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data
        git add data_error.log
        git commit -m "Auto-update processed data" || echo "No changes to commit"
        git push
