name: Calculate Ranking Metrics

on:
  workflow_run:
    workflows: ["Clean Options Data"]
    types:
      - completed
  workflow_dispatch:  # Manual trigger option

jobs:
  calculate-ranking:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Create data directory
      run: mkdir -p data

    - name: Run ranking metrics calculation
      run: |
        python -c "
        import json
        import os
        with open('data/dates.json', 'r') as f:
            dates = json.load(f)
        sources = ['yfinance', 'nasdaq']
        for ts in dates:
            for source in sources:
                os.system(f'python calculate_ranking_metrics.py {ts} {source}')
        "

    - name: Commit and push updated ranking data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data
        git commit -m "Auto-update ranking metrics data" || echo "No changes to commit"
        git push
