name: Calculate Ranking Metrics
on:
  workflow_run:
    workflows: ["Calculate Options Data"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      date:
        description: 'Date timestamp to process (e.g., 20250830_1220)'
        required: true
        type: string
jobs:
  calculate-ranking:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scipy
    - name: Create data directory
      run: mkdir -p data
    - name: Run ranking metrics calculation
      run: |
        python -c "
        import json
        import os
        timestamp = '${{ github.event.inputs.date }}' if '${{ github.event.inputs.date }}' else None
        if not timestamp:
            with open('data/dates.json', 'r') as f:
                dates = json.load(f)
            timestamp = max(dates, key=lambda x: x)
        os.system(f'python calculate_ranking_metrics.py {timestamp}')
        "
    - name: Commit and push updated ranking data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data
        git commit -m "Auto-update ranking metrics for ${{ github.event.inputs.date || 'latest timestamp' }}" || echo "No changes to commit"
        git push
    - name: Send email with yfinance ranking metrics
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Options Ranking Metrics Data"
        to: reesjmorgan@gmail.com
        from: Morgan Rees <reesjmorgan@gmail.com>
        body: |
          Attached is the latest Options ranking metrics CSV file for yfinance data.
          Timestamp: ${{ github.event.inputs.date || 'latest timestamp' }}
        attachments: |
          data/${{ github.event.inputs.date || 'latest' }}/ranking/ranking_yfinance.csv
        secure: true
