name: Fetch Options Data
on:
  schedule:
    - cron: '0 6,14,16,18,20,21 * * *' # Daily at 8 AM, 11 AM, 2 PM, 3 PM, 5 PM, 7 PM, 9 PM, 10 PM UK time
  workflow_dispatch: # Manual trigger option
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas numpy scipy # Your script's requirements
    - name: Create data directory
      run: mkdir -p data
    - name: Run fetch script
      run: python fetch_data.py
    - name: Commit and push updated data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data
        git commit -m "Auto-update raw data from scheduled fetch" || echo "No changes to commit"
        git push
