name: Fix Ticker Columns

on:
  workflow_dispatch:
    inputs:
      timestamp:
        description: 'Timestamp for data directory (e.g., 20250909_2233)'
        required: false
        default: '20250909_2233'

jobs:
  fix-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run fix script
        run: python fix_ticker_columns.py ${{ github.event.inputs.timestamp || '20250909_2233' }}

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/
          git commit -m "Fixed ticker columns in historic files for timestamp ${{ github.event.inputs.timestamp || '20250909_2233' }}" || echo "No changes to commit"
          git push
