name: Force Clean
on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date timestamp to process (e.g., 20250830_1809)'
        required: true
        type: string
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy
    - name: Create data directory
      run: mkdir -p data
    - name: Log timestamp and input files
      run: |
        echo "Running Force_Clean.py with timestamp: ${{ inputs.date }}"
        ls -R data/${{ inputs.date }}/raw_yfinance* || echo "No raw files found"
        ls -R data/${{ inputs.date }}/historic* || echo "No historic files found"
    - name: Run clean script
      run: python Force_Clean.py ${{ inputs.date }}
    - name: Log output files
      run: |
        echo "Cleaned files:"
        ls -R data/${{ inputs.date }}/cleaned_yfinance* || echo "No cleaned files found"
    - name: Commit and push updated data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data
        git commit -m "Auto-update cleaned data for ${{ inputs.date }}" || echo "No changes to commit"
        git push
