name: Preprocess Data
on:
  workflow_run:
    workflows: ["Calculate Ranking Metrics"]
    types:
      - completed
  workflow_dispatch:
jobs:
  preprocess-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scipy yfinance joblib statsmodels tqdm pyxlsb
    - name: Create data directory
      run: mkdir -p data
    - name: Run preprocess data script
      run: |
        python -c "
        import json
        import os
        with open('data/dates.json', 'r') as f:
            dates = json.load(f)
        latest_date = max(dates, key=lambda x: x)
        os.system(f'python preprocess_data.py {latest_date}')
        "
    - name: Commit and push updated data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data
        git commit -m "Auto-update precomputed tables for ${latest_date}" || echo "No changes to commit"
        git push
    - name: Send email with precomputed tables
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Precomputed Tables"
        to: reesjmorgan@gmail.com
        from: Morgan Rees <reesjmorgan@gmail.com>
        body: |
          Attached is the latest precomputed ranking table for yfinance data.
          Timestamp: ${latest_date}
        attachments: |
          data/${latest_date}/tables/ranking/ranking_table_yfinance.csv
        secure: true
