name: Restructure Yfinance Data Directory
on:
  workflow_dispatch: # Manual trigger
jobs:
  restructure:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    - name: Log initial Git status
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git status > git_status_initial.txt
    - name: Commit existing changes
      run: |
        git add .
        git commit -m "Commit existing changes before restructuring yfinance data" || echo "No existing changes to commit"
    - name: Stash any unstaged changes
      run: |
        git stash || echo "No changes to stash"
    - name: Pull and rebase
      run: |
        git pull --rebase origin main || echo "Pull rebase failed, continuing with local changes"
    - name: Reapply stashed changes
      run: |
        git stash pop || echo "No stashed changes to apply"
    - name: Run restructure script
      run: python restructure_data.py
    - name: Log final Git status
      run: |
        git status > git_status_final.txt
    - name: Commit and push restructured data
      run: |
        git add data restructure_log.txt git_status_initial.txt git_status_final.txt
        git commit -m "Restructure yfinance data into per-ticker format on $(date -u +%Y%m%d_%H%M)" || echo "No changes to commit"
        git push
    - name: Archive logs
      uses: actions/upload-artifact@v4
      with:
        name: restructure-logs
        path: |
          restructure_log.txt
          git_status_initial.txt
          git_status_final.txt
