name: Scrape Trading Economics Data
on:
  workflow_dispatch: # Manual trigger with timestamp input
    inputs:
      timestamp:
        description: 'Timestamp for the data scrape (format: YYYYMMDD_HHMM)'
        required: true
        default: '20250915_0752'

jobs:
  scrape-trading-economics:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        wget -q https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4
      continue-on-error: false
    - name: Create data directory
      run: mkdir -p data/${{ github.event.inputs.timestamp }}/Trading_Economics
    - name: Run Trading Economics scrape script
      run: |
        python -c "
        import os
        timestamp = '${{ github.event.inputs.timestamp }}'
        print(f'Running scrape_trading_economics.py with timestamp: {timestamp}')
        os.makedirs(f'data/{timestamp}/Trading_Economics', exist_ok=True)
        rc = os.system('python scrape_trading_economics.py')
        if rc != 0:
            print('Warning: scrape_trading_economics.py may have encountered issues')
        # Move CSVs to timestamped Trading_Economics directory
        if ls *.csv >/dev/null 2>&1; then
            mv *.csv data/{timestamp}/Trading_Economics/
            echo 'Moved CSVs to data/{timestamp}/Trading_Economics/'
        else
            echo 'No CSVs to move'
        fi
        "
      continue-on-error: true
    - name: Commit and push Trading Economics data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data
        git commit -m "Auto-update Trading Economics data for ${{ github.event.inputs.timestamp }}" || echo "No changes to commit"
        git push
    - name: Send email with Trading Economics data
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Trading Economics Data for ${{ github.event.inputs.timestamp }}"
        to: reesjmorgan@gmail.com
        from: Morgan Rees <reesjmorgan@gmail.com>
        body: |
          Attached is the latest Trading Economics data.
          Timestamp: ${{ github.event.inputs.timestamp }}
          Note: Some data may be missing due to scraping issues.
        attachments: |
          data/${{ github.event.inputs.timestamp }}/Trading_Economics/bonds.csv
          data/${{ github.event.inputs.timestamp }}/Trading_Economics/commodities.csv
          data/${{ github.event.inputs.timestamp }}/Trading_Economics/stocks.csv
          data/${{ github.event.inputs.timestamp }}/Trading_Economics/shares_gainers.csv
          data/${{ github.event.inputs.timestamp }}/Trading_Economics/shares_losers.csv
          data/${{ github.event.inputs.timestamp }}/Trading_Economics/currencies.csv
          data/${{ github.event.inputs.timestamp }}/Trading_Economics/crypto.csv
        secure: true
      continue-on-error: true
